### ISSUE TITLE
String and number viz patches don't update with null/undefined/empty string

### ISSUE THREAD

**Issue by positlabs** [cables-gl/cables_docs#203]
I made a test case to illustrate it: https://cables.gl/p/6230fd08e49fe06d523a87f9?s=hIILUW4U0EGPyxmz

One issue is that the patches don't visually update to show null/undefined/empty string. I'd like to know when those values change, ideally. 

Another problem is that the change listeners don't fire when setting a value to undefined, so it's not possible to react to that event downstream.

**Comment by pandrr** [comment]
hi,

- thanks for your input, i fixed the viz ops on dev.cavles.gl, the values are shown as expected there!

the change listeners only fire when the value changed. 
this is why we often have `output.set(null);output.set(thatArray);` because references to objects stay the same, but we want to comunicate a change, so we set it to null in between.

undefined is a strange javascript thing and in cables nothing ever is undefined, please dont use if for values.
in general nothing should ever be set to undefined, please use null.

**Comment by pandrr** [comment]
if you still have problems with the listeners let me know!

**Comment by positlabs** [comment]
OK, I can live with working around undefined values. I wasn't actually having trouble with those in practice but wanted to include it in the test case. 

For null and empty strings, I still think the viz patches should reflect those changes. I made a few small adjustments to the way the title is set - coercing the value into a string with JSON.stringify will make it populate the op title correctly. 

 `const str = JSON.stringify(inString.get());`
 
 Here's an example. The old value gets stuck in the op title when the actual value is null, so it can be confusing unless you know that the op title won't accept an empty string or a null.

<img width="792" alt="Screen Shot 2022-03-16 at 9 44 56 AM" src="https://user-images.githubusercontent.com/1918844/158603810-bc5f1552-5eb9-42c6-a8b4-671382247bf9.png">

**Comment by positlabs** [comment]
Oh, hah. I am still waking up :)
> thanks for your input, i fixed the viz ops on dev.cavles.gl, the values are shown as expected there!
Thanks!
