### ISSUE TITLE
AudioBufferPlayer stop time doesn't work

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#212]
I'm trying to stop a sample from playing after some time but it doesn't work.
Looking at the code, the `stop(time)`, `time` parameter is unused.

**Comment by steam0r** [comment]
hey, that's a bug. thanks for reporting. then again i think this can be patches with a delay and the start/stop boolean. the implementation regarding start/stop-time in webaudio also is a bit confusing. so even if this would be working it might not be what you want

https://github.com/WebAudio/web-audio-api/issues/2452

we are actually thining about removing these parameters, since it can be done "on the outside".

let me know if this helps and what you think
