### ISSUE TITLE
Automatic unique project names for new patches

### ISSUE THREAD

**Issue by mickeyvanolst** [cables-gl/cables_docs#310]
I have about 100x 'new project' patches in my overview. Perhaps we can automatically give random names that are legible. Glitch.com does this for instance. So each time you create a patch it has a name like "terrific blue zebra" or "abundant canary dolomite". This makes sure you can still make a low threshold quick patch without having to think of a name. 

![image](https://user-images.githubusercontent.com/1071097/184496947-d1001f46-90b9-4238-a6e0-eccbae60ffb4.png)

**Comment by mickeyvanolst** [comment]
![image](https://user-images.githubusercontent.com/1071097/184496964-95ebb39f-3dc5-4add-a103-39390a532e18.png)

**Comment by franckaubry** [comment]
Well Cables.gl actually does in the url already, so...
![image](https://user-images.githubusercontent.com/97125854/184515316-09499e4a-6c37-4b70-9297-06761f2a7630.png)

**Comment by pandrr** [comment]
ok we agree and will try it
- [ ] find list/npm of words/sentences
- [ ] create settings to turn off

**Comment by constructor** [comment]
I am not criticising this, it is a personal preference thing, but I really do not see the issue.
If a project is given a random name then what difference does it make? A random name has no context and does not describe the patch and it's functionality in any way.
If this is implemented, I would rather it be optional. Why? Because if a project is given a random name it will not be as visible as an unnamed project.
It is not a major issue, just a personal preference as I said. I have not come across a situation where this has been an issue an I prefer how it functions currently.

**Comment by steam0r** [comment]
yeah, we are also pushing this around for quite some time already, partly because of the reasons given by you. we decided to create a user-setting that turns this feature on/off once we implement it.

the "pro" is, that you sometimes have things like this, when working on patches:

![Bildschirmfoto 2022-08-24 um 12 05 31](https://user-images.githubusercontent.com/151271/186391475-27545409-a2b4-4c26-a3a7-996234f56357.png)

so remembering "the patch i am looking for was named something, something animal" might help

**Comment by steam0r** [comment]
this is available on dev.cables.gl now, default on, disablable via editor preferences in the editor. check it out!
