### ISSUE TITLE
SimpleMovingAverage OP divide by 0 bug

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#39]
The OP returns Infinity when having a division by 0.
The OR in the original OP doesn't work.

```
result.set(avg/divide||1);  // returns Infinity and not 1
```

Here is a fixed version (drop-in), which returns 0 instead on this edge case:
```
const val = op.inValue("Value");
const num = op.inValueInt("Number of Values", 10);

const result = op.outValue("Result");

val.changeAlways = true;
let buffer = [];
let index = 0;

num.onChange = init;
init();

function init()
{
    const n = Math.abs(Math.floor(num.get()));
    buffer.length = n;

    for(let i = 0; i< buffer.length;i++)
        buffer[i] = null;
    index = 0;
}

val.onChange = function() {
    index++;
    if (index >= buffer.length) index = 0;

    buffer[index] = val.get();

    let avg = 0;
    let divide = 0;
    for(let i = 0; i < buffer.length; i++) {
        if(buffer[i] !== null) { // ignore zeroes
            avg += buffer[i];
            divide++;
        }
    }

    if (divide === 0) {
        result.set(0);
    } else {
        result.set(avg/divide);
    }
};
```

**Comment by steam0r** [comment]
how can you reproduce this bug?

**Comment by kikohs** [comment]
If the number that you pass is null and that nothing else exists in the array I guess.

**Comment by steam0r** [comment]
hm, tried with null on either port, tried reloading the patch to reinitialize, never get a division by zero error, always returns 1 for "invalid values". do you have any patch where this is broken? would be really interested...

from the code the division by zero clearly "can happen" if the buffer.length is 0, which just never happens because `buffer[index] = val.get();` sets at least one element. even if it's null.

which browser is this in? is this some weird difference in how `.length` treats and array with null-values?

**Comment by steam0r** [comment]
`result.set(avg/divide||1);`  would return `0` for a division that turns out to be `0`, because of it's `falsyness`...not sure if this is correct behaviour but at least your fix would make this op "sometimes" return `0`, which it can't do at the moment...so i am kind of eager to understand what's going on here.

**Comment by kikohs** [comment]
I think I got the Infinity out of this op . The {results OR 1} would never return 1 as the Infinity value is not falsy.
My use case is not easily shareable but I could try to do a small patch (when I get back).
On 02/07/2021 10:55:13, steam0r ***@***.***> wrote:
result.set(avg/divide||1); would return 0 for a division that turns out to be 0, because of it's falsyness...not sure if this is correct behaviour but at least your fix would make this op "sometimes" return 0, which it can't do at the moment...so i am kind of eager to understand what's going on here.
