### ISSUE TITLE
Fill Array Random Duplicates Op gives undefined value in the end of array. 

### ISSUE THREAD

**Issue by bbbbbgdn** [cables-gl/cables_docs#415]
FillArrayRandomDuplicates OP gives undefined value in the end of array.

https://cables.gl/edit/fIPvAi
![image](https://user-images.githubusercontent.com/12091461/203621135-cbe499ff-ca79-4045-9707-2a524007960f.png)

**Comment by karlosgliberal** [comment]
Hello 
I have checked the code and I think the problem is in line 38. by changing 
`while (i <(num - 1))` for `while (i <= (num - 1))` is work well

The truth is that I don't know if it is possible to send these corrections through pul request or any other way. But in this case I think this solves it.

**Comment by pandrr** [comment]
thanks!
i reworked the op and its available as a new version on dev.cables.gl , it is also not needed to trigger anymore and feels more like other array ops!

**Comment by steam0r** [comment]
this is now on cables.gl with the latest release
