### ISSUE TITLE
Altered values from gemetry coordinates array

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#528]
Hi! I was testing my patches in dev and i found this using the geometry points op, the coordinates index change.

If you check this patch works good in normal cables site, but in dev not:

https://cables.gl/edit/pEfviY

i see the index of values change so it can be fixed but i guess many patches using this op will fail, i only tested this in Windows Chrome

**Comment by pandrr** [comment]
yeah i made a new version of the circle op, so the old one on dev behaves the same.

but the problem is, that you expect the geometrypoints to be unique points of a circle, they are not, they are vertices of a mesh, that are not unique and also have a center vertex at 0,0,0.

you should use PointsCircle to get unique points of a circle

**Comment by n4hui** [comment]
Ok! And thank you for the fix my patch works now as before in dev :)
