### ISSUE TITLE
Assets are public by default

### ISSUE THREAD

**Issue by NoaEilat** [cables-gl/cables_docs#531]
Hello! 

I uploaded an audio file to a private cables patch but the URL to the asset is public and anyone can access it with the right URL. 
If the patch is private I figured that the asset should be private as well. 

Thank you!

**Comment by steam0r** [comment]
you are right. this is "by design" though. cables ops take their assets as normal urls, that also goes for assets uploaded to cables itself. if we would have to protect these assets we'd have to put a lot of protection in place to make this work with, for example the iframe-export. also cloning a patch would be really weird (so some collaborator uploaded a file to a patch that is private, now you clone it but do not take the collaborator along...do you still have access to that asset, should we copy it over?)

the urls are a combination of a long id (which we hardly show anywhere else) and the filename tough. so it should not be easy to guess. if you need your assets protected somehow put them on another service, as all the ops working with assets take a normal URL as an input as well.

again, for your private patches assets are protected by the url being hard to guess. for public patches they are public anyhow. once you export your patch these assets will come with the export and you can protect them however you see fit.
